# Generated by Django 4.2.15 on 2024-08-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_excerpt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update_on",
            new_name="updated_on",
        ),
    ]
