# Generated by Django 4.2.15 on 2024-08-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_update_on_post_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
