# Generated by Django 4.2.15 on 2024-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blog",
            "0008_alter_comment_created_on_alter_post_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, default="Expect default text"),
            preserve_default=False,
        ),
    ]
